service: cspace-sas-sync

# TODO: https://www.serverless.com/framework/docs/providers/aws/guide/services#version-pinning

custom:
  sas_config: ./config/example.yml

provider:
  memorySize: 128
  name: aws
  region: us-west-2
  runtime: python3.8
  timeout: 300

functions:
  sync:
    name: cspace-sas-sync
    handler: sas/sync.handler
    events: ${file(${env:SAS_CFG, self:custom.sas_config}):sync}

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-python-requirements
