sync:
  - schedule:
      # 6.30am UTC
      rate: cron(30 6 * * ? *)
      enabled: true
      input:
        services_url: ${ssm:cspace_gsd_services_url}
        authtype: vocabularies
        refname: urn:cspace:name(materialuse)
        username: ${ssm:cspace_gsd_username~true}
        password: ${ssm:cspace_gsd_password~true}
